// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Returns 200 if the service is alive.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/keys/{keyHash}": {
            "get": {
                "description": "Retrieves the current value hash for a specific key hash, along with timestamp and slot information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get Value Hash by Key Hash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key hash (hex encoded)",
                        "name": "keyHash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Value hash with timestamp and slot",
                        "schema": {
                            "$ref": "#/definitions/database.ValueHashWithTimestamp"
                        }
                    },
                    "400": {
                        "description": "Invalid key hash format",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Key not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/objects": {
            "get": {
                "description": "Retrieves a paginated list of all tracked object IDs from the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get All Object IDs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 20, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of object IDs",
                        "schema": {
                            "$ref": "#/definitions/database.GetAllObjectIDsResult"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/objects/active": {
            "get": {
                "description": "Retrieves a paginated list of object IDs that have at least one non-deleted key from the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get Active Object IDs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 20, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of active object IDs",
                        "schema": {
                            "$ref": "#/definitions/database.GetAllObjectIDsResult"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/objects/deleted": {
            "get": {
                "description": "Retrieves a paginated list of object IDs that have no non-deleted keys from the database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get Deleted Object IDs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of items per page (default: 20, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of items to skip (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of deleted object IDs",
                        "schema": {
                            "$ref": "#/definitions/database.GetAllObjectIDsResult"
                        }
                    },
                    "400": {
                        "description": "Invalid query parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/objects/{id}": {
            "get": {
                "description": "Retrieves an object by its ID from the database with key-value pairs. Optionally specify a timestamp or slot to get historical state.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get Object by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 timestamp to get object state at specific time (e.g. 2024-01-15T10:30:00Z). Cannot be used with slot parameter.",
                        "name": "timestamp",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Slot number to get object state at specific slot. Cannot be used with timestamp parameter.",
                        "name": "slot",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Object data with timestamp and slot",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid ID format, timestamp, slot, or conflicting parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Object not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/objects/{id}/keys/{key}": {
            "get": {
                "description": "Retrieves the current value for a specific object ID and key name, along with keyHash, timestamp and slot information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "objects"
                ],
                "summary": "Get Value by Key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Key name",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Value with keyHash (hex), timestamp and slot",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Key not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/publish": {
            "post": {
                "description": "Publishes custom oracle data on-chain immediately, bypassing the updateInterval. Items may include \"object_id\"; if missing it will be generated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Publish Custom Data Immediately",
                "parameters": [
                    {
                        "description": "Oracle data to publish",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.PublishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PublishResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Chain event processor not available",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/statistics/costs": {
            "get": {
                "description": "Retrieves transaction fee statistics including total fees, averages, min/max values, and slot information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Get Cost Statistics",
                "responses": {
                    "200": {
                        "description": "Cost statistics",
                        "schema": {
                            "$ref": "#/definitions/database.CostStatistics"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.PublishRequest": {
            "type": "object",
            "required": [
                "data"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                }
            }
        },
        "api.PublishResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "txHash": {
                    "type": "string"
                }
            }
        },
        "database.CostStatistics": {
            "type": "object",
            "properties": {
                "averageFee": {
                    "type": "number"
                },
                "earliestSlot": {
                    "type": "integer"
                },
                "latestSlot": {
                    "type": "integer"
                },
                "maxFee": {
                    "type": "integer"
                },
                "minFee": {
                    "type": "integer"
                },
                "totalFees": {
                    "type": "integer"
                },
                "totalTransactions": {
                    "type": "integer"
                }
            }
        },
        "database.GetAllObjectIDsResult": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "objectIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "database.ValueHashWithTimestamp": {
            "type": "object",
            "properties": {
                "proof": {
                    "type": "string"
                },
                "slot": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "valueHash": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "Object Queries",
            "name": "objects"
        },
        {
            "description": "System status and health monitoring endpoints",
            "name": "system"
        },
        {
            "description": "Statistics and analytics endpoints",
            "name": "statistics"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Merkle Oracle Node API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
